CIT/CIT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cit2020.urls')),
    path('auth/', include('django.contrib.auth.urls')), 
    path('oauth/', include('social_django.urls', namespace='social')),
]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CIT/cit2020/urls.py
from django.urls import path
from . import views

app_name='cit2020'
urlpatterns = [
    path('', views.index, name='index'),
    path('answer/', views.answer , name='answer'),
    path('lboard/<int:slot>', views.lboard , name='lboard'),
    path('lboard/', views.lboard , name='lboard'),
    path('rules/', views.rules , name='rules'),
    path('about/', views.about, name='about'),
    path('navPage/', views.navPage, name='navPage'),
    path('forms/', views.forms , name='forms'),
    path('quiz/', views.quiz , name='quiz'),
    path('profile/', views.view_profile , name='view_profile'),
    path('profile/update', views.update_profile , name='update_profile'),
    path('qualify/<int:cutoff>', views.qualify , name='qualify'),
]

CIT/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load widget_tweaks %}
  <style>
        .outerBorder-instruct {
            position: absolute;
            display: flex;
            border: 2px solid #fff;
            width: 95%;
            top: 2.5%;
            border-radius: 3rem;
            justify-content: center;
            align-items: center;
            align-content: center;
        }

        .glowing-circle {

            -webkit-animation: glowing 1s ease-in-out infinite alternate;
            -moz-animation: glowing 1s ease-in-out infinite alternate;
            animation: glowing 1s ease-in-out infinite alternate;
        }

        @keyframes glowing {
          from {
            box-shadow: 0 0 1px #fff, 0 0 2px #fff, 0 0 3px #ffffff,
              0 0 4px rgba(0, 0, 0, 0), 0 0 5px #ffffff,
              0 0 6prgba (0, 0, 0, 0) F0, 0 0 7px #ffffff;
          }
    
          to {
            box-shadow: 0 0 2px #ffffff, 0 0 3px #ffffff, 0 0 4px #ffffff,
              0 0 5px #ffffff, 0 0 6px #ffffff, 0 0 7px #ffffff, 0 0 8px #ffffff;
          }
        }

        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            font-family : Montserrat;
            color : white;
        }

        .containerinstructionpage-1 {
            height: cover;
            top:4.5rem;
            position: relative;
            padding-bottom: 10rem;
            margin-bottom: 3rem;
        }
        .containerinstructionpage-2{
          display: flex;
          flex-direction: column;
          text-align: center;
        }

        .continstructionpage {
            display: flex;
            flex-direction: row;
        }

        .logo-imageinstructionpage {
            position: absolute;
            width: 7rem;
            height: auto;
            top: 1rem;
            left: 1rem;
        }

        .main-headinginstructionpage {
            border-style: solid;
            border-width: 1;
            border-color: #fff;
            border-radius: 30px;
            padding: 10px 25px;
            position: relative;
            top: 2rem;
            font-size: 40px;
            color: rgb(77, 150, 233);
            background-color: rgba(83, 174, 219, 0.155);
            text-align: center;
            font-family : MonsOlympia;
            letter-spacing : 5px;
        }
        .txtOnImage{
          position: absolute; 
          top: 45%; 
          left: 45%; 
          transform: translate(-50%, -50%); 
          color: white; 
          font-size: 2rem; 
          margin-left: 5rem;
          text-align: center;
          font-family: moto;
          letter-spacing: 0.5em;
        }

        .headerImg{
          width: 30rem;
        }

        .parainstructionpage {
            color: white;
            font-size: 20px;
        }

        li{
            font-size: 20px;
        }

        .slotBlock{
            padding : 8px 20px;
        }

        .slotBlock li{
            color:white;
            font-size: 18px;
        }

        .rulesHeader{
            margin-top : 3rem;
            margin-bottom : 3rem;
        }

        .main-headinginstructionpage1 {
            border-style: solid;
            border-width: 1;
            border-color: rgba(98, 159, 228, 0.781);
            border-radius: 30px;
            padding: 10px 20px;
            font-size: 40px;
            border-left-style: none;
            color: rgb(77, 150, 233);
            background-color: rgba(83, 174, 219, 0.155);
            text-align: center;
            align-self: flex-end;
            font-family : MonsOlympia;
            letter-spacing : 5px;
        }
        
        {% comment %} back button {% endcomment %}
    .backButton{
        position: absolute;
        border: 2px solid #fff;
        font-family: moto;
        border-radius: 1rem;
        font-size: 1.5rem;
        padding: 0px 10px;
        right:1.5%;
        top:2%;
        color: #fff;
        background-color:#0000004d;
        text-align: center;
    }

    .backButton:hover{
        background-color:white;
        transform: scale(1.1);
    }

    .glowing-circle-backButton {
    
        -webkit-animation: glowing 2s ease-in-out infinite alternate;
        -moz-animation: glowing 2s ease-in-out infinite alternate;
        animation: glowing 2s ease-in-out infinite alternate;
    }

    .cont{
        height: 0px;
        margin-bottom: 8rem;
    }
    {% comment %}  {% endcomment %}
   
        /* For mobile */

        @media screen and (max-width: 600px) {
            .backButton{
                right:1.7rem;
                top:1.7rem;
            }
            
            .logo-imageinstructionpage {
                position: absolute;
                width: 5rem;
                height: auto;
                top: 1rem;
                left: 1rem;
            }

            .main-headinginstructionpage {
                border-style: solid;
                border-width: 1;
                border-color: rgba(98, 159, 228, 0.781);
                border-radius: 30px;
                padding: 10px 20px;
                position: relative;
                top: 4rem;
                font-size: 30px;
                border-left-style: none;
                font-family : MonsOlympia;
                color: rgb(77, 150, 233);
                background-color: rgba(83, 174, 219, 0.155);
                text-align: center;
            }

            .main-headinginstructionpage1 {
                font-size: 25px;
            }

            .containerinstructionpage-2{
                margin-left : 10px;
            }

            .parainstructionpage {
                color: white;
                padding-top : 0.4rem;
                font-size: 18px;
            }

            .parainstructionpageRules{
                padding-top : 0rem;
            }

            li{
                font-size: 18px;
            }
    

            .containerinstructionpage-1 {
                margin: 0px;
                margin-bottom: 3rem;
            }
            .txtOnImage{
              position: absolute; 
              top: 45%; 
              left: 45%; 
              transform: translate(-50%, -50%); 
              color: white; 
              font-size: 1.2rem; 
              margin-left: 3rem;
              text-align: center;
              font-family: moto;
              letter-spacing: 0.5em;
            }
    
            .headerImg{
              width: 20rem;
            }
        }
    </style>

    <div class="outerBorder-instruct glowing-circle">
        {% if user.is_anonymous %}
            <a href="{% url 'cit2020:index' %}"><button type="button" class="btn backButton glowing-circle-backButton"><</button></a>
        {% else %}    
            <a href="{% url 'cit2020:navPage' %}"><button type="button" class="btn backButton glowing-circle-backButton"><</button></a>
        {% endif %}
        <a href="{% url 'cit2020:navPage' %}"><img class="logo-imageinstructionpage" src="{% static './Assets/whiteIste.png'%}" /></a>
        <div class="container containerinstructionpage-1">
          <div style="position: relative; text-align: center;">
            <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="About">
            <div class="txtOnImage">About&nbsp;&nbsp;?</div>
         </div>
          <div class="containerinstructionpage-2">
            <p class="parainstructionpage">
            <h1 style="font-family: ethno;">Cognitive Intelligence Test 7.0</h1>
            <p>CIT 7.0 is one-of-a-kind opportunity for all aspiring students as we unveil exhilarating challenges of national standard over the realms of basic mathematical aptitude, logical & verbal reasoning, and data interpretation. Not only does CIT implant an idea of various acclaimed aptitude tests like CAT, but our flagship event also never fails to provide a simulation of the overall screening procedure of the hiring companies. This is the most anticipated online event to compete for intellectual glory among multitude of striving contestants.</p>
            <br>
            <br>
            <h2 style="font-family: ethno;">Schedule For CIT 7.0</h2>
            <h6 style="font-family: ethno;">Preliminary Round:</h6> Candidates can attempt CIT only once in any of the three available slots:
            <li><b>Slot 1:</b> January 18, 2023 (9:00 PM - 9:45 PM)</li>
            <li><b>Slot 2:</b> January 19, 2023 (9:00 PM - 9:45 PM)</li>
            <li><b>Slot 3:</b> January 20, 2023 (9:00 PM - 9:45 PM)</li>
            <h6 style="font-family: ethno;">Final Round:</h6> Candidates selected for final round will receive a mail with details
            <li><b>Final:</b> January 22, 2023 (9:00 PM - 9:45 PM)</li>
            <br>
            <br> 
            </p>
            <div class="prize-section">
              <h2><strong>Cash PRIZES worth 3K For CIT 7.0</strong>
              {% comment %} <img src="{% static 'Assets/ims.png'%}" alt="PRIZES"> {% endcomment %}
            </div>
            <br>
            <br>
            <div style="font-family: ethno;">
              <h2>EVENT SPONSOR <br> <br>
                <img src="{% static 'Assets/ims.png'%}" alt="IMS" style="margin-right: 10px; padding-bottom: 0; border-radius: 15px;">
                {% comment %} <img src="{% static 'Assets/iocl.png'%}" alt="IOCL"
                style="padding-bottom: 0; border-radius: 15px; margin-right: 10px;"> {% endcomment %}
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

CIT/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="CIT 2024 ISTE NIT Durgapur" />
    <link rel="stylesheet" href="">
    <meta name="author" content="Avinash Yeddu" />
    <link rel="icon" type="image/x-icon" href={% static 'Assets/whiteIste.png'%}>
    <title>Cognitive Intelligence Test 7.0</title>

    {% comment %} <link
      rel="icon"
      href="{% static 'img/iste_new_logo.jpg'%}"
      type="image/x-icon"
    /> {% endcomment %}

    <!-- bootstrap css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script src="https://kit.fontawesome.com/66aa7c98b3.js" crossorigin="anonymous"></script>

    <!-- custom css styles -->
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/indexStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/formSlotStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/form_page_Styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navStyles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/profile_page.css' %}" />
    <link rel="stylesheet" href="{% static 'css/lBoardStyles.css' %}" />
    {% endcomment %}

    <!-- fonts  -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap"
      rel="stylesheet"
    />
    <style>
      ::-webkit-scrollbar {
        display: none;
       }
       body {
        -ms-overflow-style: none; /* Internet Explorer 10+ */
        scrollbar-width: none; /* Firefox */
       }
      @font-face {
        font-family: moto;
        src: url({% static './fonts/moto-verse.ttf'%});
      }
    
    @font-face {
        font-family: antonio;
        src: url({% static './fonts/Antonio-Regular.ttf'%});
      }
    
    @font-face {
        font-family: ethno;
        src: url({% static './fonts/ethnocentric_rg.otf'%});
     }
      body {
        height: 100vh;
        background-image: url({% static './Assets/bg.webp' %});
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        background-color : #061E4C;
        overflow-y: scroll;
        -webkit-overflow-scrolling:touch;
    }
    </style> 
    {% block cssStyles %} {% endblock %}
  </head>

  <body>

    {% block content %} {% endblock %}
    <script>
      window.ondevtoolopen = function() {
        alert('Developer tools opened!');
    };
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

CIT/templates/finish.html
{% extends 'base.html' %}
{%block content%}
{% load static %}

<style>
    * {
        padding: 0;
        margin: 0;
    }
    
    body {
        overflow-y: hidden;
        font-family: ethno;
        font-weight: 400;
    }
    
    .finish-container {
        {% comment %} background-image: url('{% static './Assets/bg.png'%}'); {% endcomment %}
        background-size: cover;
        height: 100vh;
        padding: 20px;
    }
    
      .outerBorder {
          position: fixed;
          border: 2px solid #fff;
          width: 95%;
          height: 95%;
          top: 2.5%;
          left: 2.5%;
          border-radius: 3rem;
          justify-content: center;
          align-items: center;
          align-content: center;
      }
    
    .glowing-circle {
    
        -webkit-animation: glowing 1s ease-in-out infinite alternate;
        -moz-animation: glowing 1s ease-in-out infinite alternate;
        animation: glowing 1s ease-in-out infinite alternate;
    }
    
    @keyframes glowing {
        from {
          box-shadow: 0 0 1px #fff, 0 0 2px #fff, 0 0 3px #ffffff,
            0 0 4px rgba(0, 0, 0, 0), 0 0 5px #ffffff,
            0 0 6prgba (0, 0, 0, 0) F0, 0 0 7px #ffffff;
        }
    
        to {
          box-shadow: 0 0 2px #ffffff, 0 0 3px #ffffff, 0 0 4px #ffffff,
            0 0 5px #ffffff, 0 0 6px #ffffff, 0 0 7px #ffffff, 0 0 8px #ffffff;
        }
      }
    
    .container-1 {
        border-style: solid;
        border-radius: 50px;
        border-width: 2;
        border-color: white;
        color: #fff;
        height: cover;
      
    }
    
    .container-fluid {
        display: flex;
        height : 95vh;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    
    .cont {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }
    
    .image {
        position: absolute;
        width: 7rem;
        height: auto;
        left: 1rem;
        top: 1rem;
    }
    
    .para-1 {
        color: white;
        font-size: 2rem;
        text-align: center;
        text-align: center;
        font-style: normal;
        font-weight: 400;
        font-family: ethno;
        letter-spacing : 5px;
        margin-top: 10px;
    }
    
    .para-2 {
        color: white;
        font-size: 1.5rem;
        text-align: center;
        text-align: center;
        font-style: normal;
        font-weight: 400;
        font-family: ethno;
        letter-spacing : 5px;
    }
    
    .para-3 {
        color: white;
        font-size: 1.5rem;
        text-align: center;
        text-align: center;
        font-style: normal;
        font-weight: 400;
        font-family: ethno;
        letter-spacing : 5px;
    }
    
    .backButton{
        position: absolute;
        border: 2px solid #fff;
        border-radius: 1rem;
        font-size: 1.5rem;
        padding: 0px 10px;
        right:4%;
        top:5%;
        font-family: moto;
        color: white;
        background-color:#0000004d;
        text-align: center;
        z-index : 100;
    }
    
    .backButton:hover{
        background-color:white;
        transform: scale(1.1);
    }
    
    .glowing-circle-backButton {
    
        -webkit-animation: glowing 2s ease-in-out infinite alternate;
        -moz-animation: glowing 2s ease-in-out infinite alternate;
        animation: glowing 2s ease-in-out infinite alternate;
    }

    @media screen and (max-width: 600px) {

        .backButton{
            top:8%;
            right:7%;
        }
    
        .image {
            width: 4rem;
        }
    
    
        .para-1 {
            color: white;
            margin-top: 10px;
            font-size: 1rem;
            text-align: center;
            font-style: normal;
            font-weight: 100;
        }
    
        .para-2 {
            color: white;
            padding-top: 30px;
            font-size: 0.5rem;
            text-align: center;
            font-style: normal;
            font-weight: 300;
        }
    
        .para-3 {
            color: white;
            padding-top: 30px;
            font-size: 1.25rem;
            text-align: center;
            font-style: normal;
            font-weight: 400;
        }
    }
</style>


<div class = "finish-container">
    <a href="{% url 'cit2020:navPage' %}"> <button type="button" class="btn backButton glowing-circle-backButton"><</button></a>
    <div class="container-1 outerBorder glowing-circle">
        <div class="text-center cont">
            <a href="{% url 'cit2020:navPage' %}"><img class="image" src="{% static './Assets/whiteIste.png'%}" /></a>
        </div>
        <div class="container-fluid">
            {% if user and not user.is_anonymous %}
             <h2 class = "para-1"><strong>TEST FINISHED</strong></h2class>
            {% if player.qualified == True %}
             <h2 class = "para-1"><strong>Your Preliminary Round Score : <span style="color:#0d6efd">{{player.score}}</span> <br> <br> Final Round Score : <span style="color:#0d6efd">{{player.final_score}}</span></strong></h2>
            <h2 class = "para-1"><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' %}"> LEADERBOARD </a> for Rank</strong></h2class>
            {% else %}
            <h2 class = "para-1"><strong>Your Preliminary Round Score is <span style="color:#0d6efd">{{player.score}}</span></strong></h2>
            <h2 class = "para-1"><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' slot=player.slot %}"> LEADERBOARD </a> for Rank</strong></h2>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>


{%endblock%}

CIT/templates/navigation_page.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<style>
  body {
    font-family: MonsOlympia;
  }

  body {
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
  }

  .btn:before {
    content: "";
    top: 0;
    left: 0;
    width: 0%;
    height: 100%;
    background: rgba(255, 255, 255, 0.1);
  }

  .btn:after {
    content: "";
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 100%;
    background: linear-gradient(
      90deg,
      transparent,
      rgba(255, 255, 255, 0.4),
      transparent
    );
    transition: 0.5s;
    transition-delay: 0.1s;
  }

  .btn:hover {
    text-decoration: none;
    color: #4ebaf0;
    transform: scale(1.1);
  }

  .btn:hover:after {
    left: 100%;
  }

  .outerBorder-navPage {
    position: absolute;
    border: 2px solid #fff;
    width: 95%;
    top: 2.5%;
    left: 2.5%;
    border-radius: 3rem;
    justify-content: center;
    align-items: center;
    align-content: center;
    min-height: 95%;
  }

  .navButton {
    margin-top: 1rem;
  }

  .rounded-corners-gradient-borders-navPage {
    border: double 2px transparent;
    border-radius: 20px;
    background-image: linear-gradient(
        rgba(0, 0, 0, 0.542),
        rgba(0, 0, 0, 0.542)
      ),
      linear-gradient(#2241cb, #0018223b);
    background-origin: border-box;
    background-clip: padding-box, border-box;
    box-shadow: 0 5px 5px rgba(0, 0, 0.2);
  }

  .glowing-circle {
    -webkit-animation: glowing 1s ease-in-out infinite alternate;
    -moz-animation: glowing 1s ease-in-out infinite alternate;
    animation: glowing 1s ease-in-out infinite alternate;
  }

  .buttonBox-nav {
    height: 95vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  

  @keyframes glowing {
    from {
      box-shadow: 0 0 1px #fff, 0 0 2px #fff, 0 0 3px #ffffff,
        0 0 4px rgba(0, 0, 0, 0), 0 0 5px #ffffff,
        0 0 6prgba (0, 0, 0, 0) F0, 0 0 7px #ffffff;
    }

    to {
      box-shadow: 0 0 2px #ffffff, 0 0 3px #ffffff, 0 0 4px #ffffff,
        0 0 5px #ffffff, 0 0 6px #ffffff, 0 0 7px #ffffff, 0 0 8px #ffffff;
    }
  }

  .logoutBtn{
    background-color : #0000004d;
    display:flex;
    align-items: center;
    justify-content: center;
    width: 11rem !important;
    padding-left: 2rem !important;
    color: white !important;
    font-family: moto;
    border: 2px solid #fff;
    border-radius: 1rem;
  }

  .txtOnImage{
    position: absolute; 
    top: 45%; 
    left: 45%; 
    transform: translate(-50%, -50%); 
    color: white; 
    font-size: 1.3rem; 
    margin-left: 1rem;
    text-align: center;
    font-family: moto;
  }

  .headerImg{
    width: 30rem;
    height: 6rem;
  }

  .icon{
    position: relative;
    left: 4.5rem;
  }

  /* For desktop */

  @media (min-width: 656px) {
    .logo-nav img {
      position: absolute;
      width: 7rem;
      height: auto;
      top: 1rem;
      left: 1rem;
    }


    .btn {
      position: relative;
      padding: 20px 50px;
      top: -5%;
      width: 25rem;
      text-decoration: none;
      color: #4ebaf0;
      font-size: 150%;
      text-transform: uppercase;
      letter-spacing: 4px;
      overflow: hidden;
    }
    .logoutBtn{
      position: absolute;
      top: 1rem;
      right: 1rem;
      width : 12rem;
      height: 10%;
      font-size : 1rem;
      padding: 5px 20px;
    }
  }

  /* For mobiles */
  @media (min-width: 200px) and (max-width: 656px) {
    .btn {
      position: relative;
      padding: 15px 20px;
      width: 15rem;
      top: 10%;
      text-decoration: none;
      color: #4ebaf0;
      font-size: 1em;
      text-transform: uppercase;
      letter-spacing: 4px;
      overflow: hidden;
    }
    .txtOnImage{
      position: absolute; 
      top: 45%; 
      left: 45%; 
      transform: translate(-50%, -50%); 
      color: white; 
      font-size: 1rem; 
      margin-left: 1rem;
      text-align: center;
      font-family: moto;
    }
  
    .headerImg{
      width: 20rem;
      height: 5rem;
    }
    .start-icon{
      left:4.5rem !important;
    }
    .about-icon{
      left:4.5rem !important;
    }
    .instructions{
      font-size: 0.8rem !important;
    }
    .instructions-icon{
      left:2.5rem !important;
    }
    .leaderboard{
      font-size: 0.8rem !important;
    }
    .leaderboard-icon{
      left:2.5rem !important;
    }
    .profile{
      font-size: 0.8rem !important;
    }
    .profile-icon{
      left: 3rem !important;
    }
    .logo-nav img {
      position: absolute;
      width: 5rem;
      height: auto;
      top: 1rem;
      left: 1rem;
    }

    .buttonBox-nav {
      margin-top: 0rem;
    }

    .logoutBtn{
      position: absolute;
      top:1rem;
      right: 1rem;
      font-size: 0.8rem !important;
      width: 6rem !important;
      padding-left: 1rem !important;
    }
    .logoutBtn img{
      width: 2.2rem;
      position: relative;
      left: 0rem;
    }
  }
  .logoutBtn:hover{
    transform: scale(1.09);
  }
  .buttonBox-nav a:hover{
    img{
      filter: grayscale(1);
    }
  }

.glowing-circle-backButton {

    -webkit-animation: glowing 2s ease-in-out infinite alternate;
    -moz-animation: glowing 2s ease-in-out infinite alternate;
    animation: glowing 2s ease-in-out infinite alternate;
}
  
  .buttonBox-nav a:hover i{
    color:cyan;
    transform: scale(1.3);
  }
</style>

<div class="outerBorder-navPage glowing-circle">
  <div class="logo-nav text-left">
    
    <a href="{% url 'cit2020:index' %}">
      <img src="{% static './Assets/whiteIste.png'%}" alt="ISTE Logo" />
    </a>
  </div>
  <div class="buttonBox-nav">
    {% csrf_token %}
    {% if user.is_authenticated %}
    <a href="{% url 'cit2020:quiz' %}">
      <div style="position: relative; text-align: center; margin-top: 4rem;">
        <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="Start">
        <div class="txtOnImage start">Start<i class="fa fa-play icon start-icon" style="left:7.5rem"></i></div>
     </div></a
    >
    {% endif %}
    <br />
    <a href="{% url 'cit2020:about' %}">
      <div style="position: relative; text-align: center;">
        <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="about">
        <div class="txtOnImage about">About<i class="fa fa-question icon about-icon" style="left:7.5rem"></i></div>
     </div>
      
    </a>
    <br />
    <a href="{% url 'cit2020:rules' %}">
      <div style="position: relative; text-align: center;">
        <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="Instructions">
        <div class="txtOnImage instructions">Instructions<i class="fa fa-book icon instructions-icon" style="left:4rem"></i></div>
     </div>
    </a>
    <br />
    <a href="{% url 'cit2020:lboard' %}">
      <div style="position: relative; text-align: center;">
        <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="Leaderboard">
        <div class="txtOnImage leaderboard" style="font-size: 1.25rem;">Leaderboard<i class="fa fa-star icon leaderboard-icon" style="left:4rem"></i></div>
     </div>
    </a>
    <br />
    {% if user.is_authenticated %}
    <a href="{% url 'cit2020:view_profile' %}">
      <div style="position: relative; text-align: center;">
        <img class="headerImg" src="{% static "./Assets/title.png" %}" alt="Profile">
        <div class="txtOnImage profile">View Profile<i class="fa fa-user icon profile-icon" style="left:4.2rem"></i></div>
     </div>
    </a>
    {% endif %}
    <br />

    {% comment %}
    <button
      type="button"
      class="btn start rounded-corners-gradient-borders-navPage navButton"
      onclick="location.href='{% url 'quiz' %}'"
    >
      start
    </button>
    {% endcomment %}
  </div>
  {% if user.is_authenticated %}
  <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit" class="start navButton glowing-circle-backButton logoutBtn">Log Out<img src="{% static "./Assets/logout.png" %}" alt=""></button>
  </form>
</div>
<script> function handleLogoutClick(event) { event.preventDefault(); window.location = {% url 'logout' %}; } </script>
{% endif %}
{% endblock %}